# Generated by Django 4.2.6 on 2024-01-17 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img3',
            field=models.ImageField(blank=True, upload_to='products/thum/', verbose_name='fouth image'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='car models')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('holder', models.CharField(max_length=900)),
                ('vehicle_id', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=1000, max_length=7)),
                ('description', models.TextField(max_length=100)),
                ('category', models.CharField(choices=[('F', 'Bus'), ('D', 'Heavy Load'), ('E', 'Light Load'), ('G', 'Truck'), ('H', 'Bicycle'), ('A', 'Motor Cycle'), ('B', 'Light Passenger'), ('C', 'Heavy Passenger')], max_length=1)),
                ('status', models.CharField(choices=[('SV', 'Scrapped'), ('UV', 'Used'), ('NV', 'New'), ('RV', 'Rebuild')], max_length=2)),
                ('vehicle_certificate', models.ImageField(blank=True, upload_to='vehicle/detail/', verbose_name='image')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.city')),
                ('color', models.ManyToManyField(blank=True, null=True, to='product.color')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.province')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.tag')),
            ],
        ),
    ]
