# Generated by Django 4.2.6 on 2024-01-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_img3_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('H', 'Bicycle'), ('A', 'Motor Cycle'), ('D', 'Heavy Load'), ('F', 'Bus'), ('C', 'Heavy Passenger'), ('B', 'Light Passenger'), ('E', 'Light Load'), ('G', 'Truck')], max_length=1),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('RV', 'Rebuild'), ('SV', 'Scrapped'), ('UV', 'Used'), ('NV', 'New')], max_length=2),
        ),
    ]
