# Generated by Django 4.2.6 on 2024-01-17 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_vehicle_category_alter_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location_city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_city', to='product.city'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('C', 'Heavy Passenger'), ('D', 'Heavy Load'), ('G', 'Truck'), ('B', 'Light Passenger'), ('E', 'Light Load'), ('H', 'Bicycle'), ('A', 'Motor Cycle'), ('F', 'Bus')], max_length=1),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('NV', 'New'), ('UV', 'Used'), ('SV', 'Scrapped'), ('RV', 'Rebuild')], max_length=2),
        ),
    ]
