# Generated by Django 4.1.7 on 2024-06-18 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_category_alter_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location_city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.city'),
        ),
    ]
