# Generated by Django 4.2.6 on 2024-01-17 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_alter_product_location_city_alter_vehicle_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('D', 'Heavy Load'), ('H', 'Bicycle'), ('B', 'Light Passenger'), ('E', 'Light Load'), ('G', 'Truck'), ('C', 'Heavy Passenger'), ('A', 'Motor Cycle'), ('F', 'Bus')], max_length=1),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('NV', 'New'), ('UV', 'Used'), ('RV', 'Rebuild'), ('SV', 'Scrapped')], max_length=2),
        ),
    ]
