# Generated by Django 4.1.7 on 2024-06-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=700)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('barner', models.ImageField(upload_to='events/barner/')),
                ('img', models.ImageField(blank=True, null=True, upload_to='events/barner/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='events/barner/')),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=1000, max_length=7)),
                ('description', models.TextField(verbose_name='event description')),
                ('location', models.CharField(max_length=700)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
